// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/bridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 切换类型
type ESwitchType int32

const (
	ESwitchType_switch_immediate   ESwitchType = 1 // 立即切换
	ESwitchType_switch_after_round ESwitchType = 2 // 回合结束后切换
	ESwitchType_switch_optional    ESwitchType = 3 // 可选切换（玩家选择）
)

// Enum value maps for ESwitchType.
var (
	ESwitchType_name = map[int32]string{
		1: "switch_immediate",
		2: "switch_after_round",
		3: "switch_optional",
	}
	ESwitchType_value = map[string]int32{
		"switch_immediate":   1,
		"switch_after_round": 2,
		"switch_optional":    3,
	}
)

func (x ESwitchType) Enum() *ESwitchType {
	p := new(ESwitchType)
	*p = x
	return p
}

func (x ESwitchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESwitchType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bridge_proto_enumTypes[0].Descriptor()
}

func (ESwitchType) Type() protoreflect.EnumType {
	return &file_proto_bridge_proto_enumTypes[0]
}

func (x ESwitchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ESwitchType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ESwitchType(num)
	return nil
}

// Deprecated: Use ESwitchType.Descriptor instead.
func (ESwitchType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

// 游戏切换通知
// @name game_switch
type M_9901Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *ESwitchType           `protobuf:"varint,1,req,name=type,enum=bridge.ESwitchType" json:"type,omitempty"` // 切换类型
	FromGame      *string                `protobuf:"bytes,2,req,name=from_game,json=fromGame" json:"from_game,omitempty"`  // 源游戏
	ToGame        *string                `protobuf:"bytes,3,req,name=to_game,json=toGame" json:"to_game,omitempty"`        // 目标游戏
	Data          *PBridgeData           `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`                          // 桥接数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_9901Toc) Reset() {
	*x = M_9901Toc{}
	mi := &file_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_9901Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_9901Toc) ProtoMessage() {}

func (x *M_9901Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_9901Toc.ProtoReflect.Descriptor instead.
func (*M_9901Toc) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *M_9901Toc) GetType() ESwitchType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ESwitchType_switch_immediate
}

func (x *M_9901Toc) GetFromGame() string {
	if x != nil && x.FromGame != nil {
		return *x.FromGame
	}
	return ""
}

func (x *M_9901Toc) GetToGame() string {
	if x != nil && x.ToGame != nil {
		return *x.ToGame
	}
	return ""
}

func (x *M_9901Toc) GetData() *PBridgeData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 桥接数据
type PBridgeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreeRounds    *uint32                `protobuf:"varint,1,opt,name=free_rounds,json=freeRounds" json:"free_rounds,omitempty"`   // 免费次数
	Multiplier    *float32               `protobuf:"fixed32,2,opt,name=multiplier" json:"multiplier,omitempty"`                    // 倍率
	BonusPool     *uint64                `protobuf:"varint,3,opt,name=bonus_pool,json=bonusPool" json:"bonus_pool,omitempty"`      // 奖池
	TriggerType   *string                `protobuf:"bytes,4,opt,name=trigger_type,json=triggerType" json:"trigger_type,omitempty"` // 触发类型
	TriggerPos    []uint32               `protobuf:"varint,5,rep,name=trigger_pos,json=triggerPos" json:"trigger_pos,omitempty"`   // 触发位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBridgeData) Reset() {
	*x = PBridgeData{}
	mi := &file_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBridgeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBridgeData) ProtoMessage() {}

func (x *PBridgeData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBridgeData.ProtoReflect.Descriptor instead.
func (*PBridgeData) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *PBridgeData) GetFreeRounds() uint32 {
	if x != nil && x.FreeRounds != nil {
		return *x.FreeRounds
	}
	return 0
}

func (x *PBridgeData) GetMultiplier() float32 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *PBridgeData) GetBonusPool() uint64 {
	if x != nil && x.BonusPool != nil {
		return *x.BonusPool
	}
	return 0
}

func (x *PBridgeData) GetTriggerType() string {
	if x != nil && x.TriggerType != nil {
		return *x.TriggerType
	}
	return ""
}

func (x *PBridgeData) GetTriggerPos() []uint32 {
	if x != nil {
		return x.TriggerPos
	}
	return nil
}

// Animal游戏触发通知
// @name animal_trigger_notify
type M_9903Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggered     *bool                  `protobuf:"varint,1,req,name=triggered" json:"triggered,omitempty"`                       // 是否触发
	TriggerType   *string                `protobuf:"bytes,2,req,name=trigger_type,json=triggerType" json:"trigger_type,omitempty"` // 触发类型
	BridgeData    *PBridgeData           `protobuf:"bytes,3,opt,name=bridge_data,json=bridgeData" json:"bridge_data,omitempty"`    // 桥接数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_9903Toc) Reset() {
	*x = M_9903Toc{}
	mi := &file_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_9903Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_9903Toc) ProtoMessage() {}

func (x *M_9903Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_9903Toc.ProtoReflect.Descriptor instead.
func (*M_9903Toc) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *M_9903Toc) GetTriggered() bool {
	if x != nil && x.Triggered != nil {
		return *x.Triggered
	}
	return false
}

func (x *M_9903Toc) GetTriggerType() string {
	if x != nil && x.TriggerType != nil {
		return *x.TriggerType
	}
	return ""
}

func (x *M_9903Toc) GetBridgeData() *PBridgeData {
	if x != nil {
		return x.BridgeData
	}
	return nil
}

// 游戏返回通知
// @name game_return
type M_9902Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromGame      *string                `protobuf:"bytes,1,req,name=from_game,json=fromGame" json:"from_game,omitempty"`             // 从哪个游戏返回
	BonusWin      *uint64                `protobuf:"varint,2,req,name=bonus_win,json=bonusWin" json:"bonus_win,omitempty"`            // bonus游戏赢分
	BridgeResult  *PBridgeResult         `protobuf:"bytes,3,opt,name=bridge_result,json=bridgeResult" json:"bridge_result,omitempty"` // 桥接结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_9902Toc) Reset() {
	*x = M_9902Toc{}
	mi := &file_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_9902Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_9902Toc) ProtoMessage() {}

func (x *M_9902Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_9902Toc.ProtoReflect.Descriptor instead.
func (*M_9902Toc) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *M_9902Toc) GetFromGame() string {
	if x != nil && x.FromGame != nil {
		return *x.FromGame
	}
	return ""
}

func (x *M_9902Toc) GetBonusWin() uint64 {
	if x != nil && x.BonusWin != nil {
		return *x.BonusWin
	}
	return 0
}

func (x *M_9902Toc) GetBridgeResult() *PBridgeResult {
	if x != nil {
		return x.BridgeResult
	}
	return nil
}

// 桥接结果
type PBridgeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalWin      *uint64                `protobuf:"varint,1,req,name=total_win,json=totalWin" json:"total_win,omitempty"`   // 总赢分
	Achievements  *uint32                `protobuf:"varint,2,opt,name=achievements" json:"achievements,omitempty"`           // 成就数量
	ExtraData     *string                `protobuf:"bytes,3,opt,name=extra_data,json=extraData" json:"extra_data,omitempty"` // 额外数据(JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBridgeResult) Reset() {
	*x = PBridgeResult{}
	mi := &file_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBridgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBridgeResult) ProtoMessage() {}

func (x *PBridgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBridgeResult.ProtoReflect.Descriptor instead.
func (*PBridgeResult) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *PBridgeResult) GetTotalWin() uint64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *PBridgeResult) GetAchievements() uint32 {
	if x != nil && x.Achievements != nil {
		return *x.Achievements
	}
	return 0
}

func (x *PBridgeResult) GetExtraData() string {
	if x != nil && x.ExtraData != nil {
		return *x.ExtraData
	}
	return ""
}

var File_proto_bridge_proto protoreflect.FileDescriptor

const file_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\x12proto/bridge.proto\x12\x06bridge\"\x98\x01\n" +
	"\n" +
	"m_9901_toc\x12)\n" +
	"\x04type\x18\x01 \x02(\x0e2\x15.bridge.e_switch_typeR\x04type\x12\x1b\n" +
	"\tfrom_game\x18\x02 \x02(\tR\bfromGame\x12\x17\n" +
	"\ato_game\x18\x03 \x02(\tR\x06toGame\x12)\n" +
	"\x04data\x18\x04 \x01(\v2\x15.bridge.p_bridge_dataR\x04data\"\xb3\x01\n" +
	"\rp_bridge_data\x12\x1f\n" +
	"\vfree_rounds\x18\x01 \x01(\rR\n" +
	"freeRounds\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x02R\n" +
	"multiplier\x12\x1d\n" +
	"\n" +
	"bonus_pool\x18\x03 \x01(\x04R\tbonusPool\x12!\n" +
	"\ftrigger_type\x18\x04 \x01(\tR\vtriggerType\x12\x1f\n" +
	"\vtrigger_pos\x18\x05 \x03(\rR\n" +
	"triggerPos\"\x85\x01\n" +
	"\n" +
	"m_9903_toc\x12\x1c\n" +
	"\ttriggered\x18\x01 \x02(\bR\ttriggered\x12!\n" +
	"\ftrigger_type\x18\x02 \x02(\tR\vtriggerType\x126\n" +
	"\vbridge_data\x18\x03 \x01(\v2\x15.bridge.p_bridge_dataR\n" +
	"bridgeData\"\x84\x01\n" +
	"\n" +
	"m_9902_toc\x12\x1b\n" +
	"\tfrom_game\x18\x01 \x02(\tR\bfromGame\x12\x1b\n" +
	"\tbonus_win\x18\x02 \x02(\x04R\bbonusWin\x12<\n" +
	"\rbridge_result\x18\x03 \x01(\v2\x17.bridge.p_bridge_resultR\fbridgeResult\"q\n" +
	"\x0fp_bridge_result\x12\x1b\n" +
	"\ttotal_win\x18\x01 \x02(\x04R\btotalWin\x12\"\n" +
	"\fachievements\x18\x02 \x01(\rR\fachievements\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x03 \x01(\tR\textraData*R\n" +
	"\re_switch_type\x12\x14\n" +
	"\x10switch_immediate\x10\x01\x12\x16\n" +
	"\x12switch_after_round\x10\x02\x12\x13\n" +
	"\x0fswitch_optional\x10\x03B(Z&github.com/wfunc/slot-game/internal/pb"

var (
	file_proto_bridge_proto_rawDescOnce sync.Once
	file_proto_bridge_proto_rawDescData []byte
)

func file_proto_bridge_proto_rawDescGZIP() []byte {
	file_proto_bridge_proto_rawDescOnce.Do(func() {
		file_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)))
	})
	return file_proto_bridge_proto_rawDescData
}

var file_proto_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_bridge_proto_goTypes = []any{
	(ESwitchType)(0),      // 0: bridge.e_switch_type
	(*M_9901Toc)(nil),     // 1: bridge.m_9901_toc
	(*PBridgeData)(nil),   // 2: bridge.p_bridge_data
	(*M_9903Toc)(nil),     // 3: bridge.m_9903_toc
	(*M_9902Toc)(nil),     // 4: bridge.m_9902_toc
	(*PBridgeResult)(nil), // 5: bridge.p_bridge_result
}
var file_proto_bridge_proto_depIdxs = []int32{
	0, // 0: bridge.m_9901_toc.type:type_name -> bridge.e_switch_type
	2, // 1: bridge.m_9901_toc.data:type_name -> bridge.p_bridge_data
	2, // 2: bridge.m_9903_toc.bridge_data:type_name -> bridge.p_bridge_data
	5, // 3: bridge.m_9902_toc.bridge_result:type_name -> bridge.p_bridge_result
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_bridge_proto_init() }
func file_proto_bridge_proto_init() {
	if File_proto_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bridge_proto_goTypes,
		DependencyIndexes: file_proto_bridge_proto_depIdxs,
		EnumInfos:         file_proto_bridge_proto_enumTypes,
		MessageInfos:      file_proto_bridge_proto_msgTypes,
	}.Build()
	File_proto_bridge_proto = out.File
	file_proto_bridge_proto_goTypes = nil
	file_proto_bridge_proto_depIdxs = nil
}
