// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/cfg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取信息
// @name get_info
type M_2001Tos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2001Tos) Reset() {
	*x = M_2001Tos{}
	mi := &file_proto_cfg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2001Tos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2001Tos) ProtoMessage() {}

func (x *M_2001Tos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2001Tos.ProtoReflect.Descriptor instead.
func (*M_2001Tos) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{0}
}

type M_2001Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        *uint32                `protobuf:"varint,1,req,name=role_id,json=roleId" json:"role_id,omitempty"`
	Balance       *uint64                `protobuf:"varint,2,req,name=balance" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2001Toc) Reset() {
	*x = M_2001Toc{}
	mi := &file_proto_cfg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2001Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2001Toc) ProtoMessage() {}

func (x *M_2001Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2001Toc.ProtoReflect.Descriptor instead.
func (*M_2001Toc) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{1}
}

func (x *M_2001Toc) GetRoleId() uint32 {
	if x != nil && x.RoleId != nil {
		return *x.RoleId
	}
	return 0
}

func (x *M_2001Toc) GetBalance() uint64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

// 捕捉错误
// @name get_error
type M_2002Tos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,req,name=error" json:"error,omitempty"` // 错误内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2002Tos) Reset() {
	*x = M_2002Tos{}
	mi := &file_proto_cfg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2002Tos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2002Tos) ProtoMessage() {}

func (x *M_2002Tos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2002Tos.ProtoReflect.Descriptor instead.
func (*M_2002Tos) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{2}
}

func (x *M_2002Tos) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type M_2002Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2002Toc) Reset() {
	*x = M_2002Toc{}
	mi := &file_proto_cfg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2002Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2002Toc) ProtoMessage() {}

func (x *M_2002Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2002Toc.ProtoReflect.Descriptor instead.
func (*M_2002Toc) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{3}
}

// 心跳包
// @name heartbeat
type M_2099Tos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2099Tos) Reset() {
	*x = M_2099Tos{}
	mi := &file_proto_cfg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2099Tos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2099Tos) ProtoMessage() {}

func (x *M_2099Tos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2099Tos.ProtoReflect.Descriptor instead.
func (*M_2099Tos) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{4}
}

type M_2099Toc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M_2099Toc) Reset() {
	*x = M_2099Toc{}
	mi := &file_proto_cfg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M_2099Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M_2099Toc) ProtoMessage() {}

func (x *M_2099Toc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cfg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M_2099Toc.ProtoReflect.Descriptor instead.
func (*M_2099Toc) Descriptor() ([]byte, []int) {
	return file_proto_cfg_proto_rawDescGZIP(), []int{5}
}

var File_proto_cfg_proto protoreflect.FileDescriptor

const file_proto_cfg_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/cfg.proto\x12\x03cfg\"\f\n" +
	"\n" +
	"m_2001_tos\"?\n" +
	"\n" +
	"m_2001_toc\x12\x17\n" +
	"\arole_id\x18\x01 \x02(\rR\x06roleId\x12\x18\n" +
	"\abalance\x18\x02 \x02(\x04R\abalance\"\"\n" +
	"\n" +
	"m_2002_tos\x12\x14\n" +
	"\x05error\x18\x01 \x02(\tR\x05error\"\f\n" +
	"\n" +
	"m_2002_toc\"\f\n" +
	"\n" +
	"m_2099_tos\"\f\n" +
	"\n" +
	"m_2099_tocB(Z&github.com/wfunc/slot-game/internal/pb"

var (
	file_proto_cfg_proto_rawDescOnce sync.Once
	file_proto_cfg_proto_rawDescData []byte
)

func file_proto_cfg_proto_rawDescGZIP() []byte {
	file_proto_cfg_proto_rawDescOnce.Do(func() {
		file_proto_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cfg_proto_rawDesc), len(file_proto_cfg_proto_rawDesc)))
	})
	return file_proto_cfg_proto_rawDescData
}

var file_proto_cfg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cfg_proto_goTypes = []any{
	(*M_2001Tos)(nil), // 0: cfg.m_2001_tos
	(*M_2001Toc)(nil), // 1: cfg.m_2001_toc
	(*M_2002Tos)(nil), // 2: cfg.m_2002_tos
	(*M_2002Toc)(nil), // 3: cfg.m_2002_toc
	(*M_2099Tos)(nil), // 4: cfg.m_2099_tos
	(*M_2099Toc)(nil), // 5: cfg.m_2099_toc
}
var file_proto_cfg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cfg_proto_init() }
func file_proto_cfg_proto_init() {
	if File_proto_cfg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cfg_proto_rawDesc), len(file_proto_cfg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cfg_proto_goTypes,
		DependencyIndexes: file_proto_cfg_proto_depIdxs,
		MessageInfos:      file_proto_cfg_proto_msgTypes,
	}.Build()
	File_proto_cfg_proto = out.File
	file_proto_cfg_proto_goTypes = nil
	file_proto_cfg_proto_depIdxs = nil
}
